notifications:
  irc:
    channels:
      - "chat.freenode.net#detnet-sec"
    on_success: always
    on_failure: always
    template:
      - "%{repository_slug} : %{message}"
      - "%{commit} : %{author} : %{commit_subject}"
      - "Build details: %{build_url}"
language: python
addons:
  apt:
    packages:
      - bash
      - wget
      - make
install:
  - pip install -r requirements.txt

script:
  - make rebuild
